apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: polar
spec:
  selector:
    app:  catalog-service
  type:  ClusterIP
  ports:
  - protocol:  TCP
    port:  80
    targetPort:  9001